import { lightColors, darkColors } from './colors';
import { webSpacing } from './spacing';
import { webRadii } from './radii';
import { webTypography } from './typography';

const SCALE_FAMILIES = ['neutral', 'white', 'primary', 'secondary', 'success', 'error', 'warning'] as const;
const FLAT_COLOR_KEYS = [
  'background',
  'dashboardBackground',
  'buttonBackground',
  'buttonTextIconDark',
  'buttonTextIconLight',
  'cardBackground',
] as const;

export function toKebabCase(value: string) {
  return value.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();
}

export type CssVariable = { name: string; value: string };

export function colorVariables(colors: typeof lightColors | typeof darkColors): CssVariable[] {
  const entries: CssVariable[] = [];
  for (const family of SCALE_FAMILIES) {
    for (const [step, value] of Object.entries(colors[family])) {
      entries.push({ name: `--color-${family}-${step}`, value });
    }
  }
  for (const key of FLAT_COLOR_KEYS) {
    entries.push({ name: `--color-${toKebabCase(key)}`, value: colors[key] });
  }
  return entries;
}

export function spacingVariables(scale: Record<string, number> = webSpacing): CssVariable[] {
  return Object.entries(scale).map(([key, value]) => ({ name: `--${key}`, value: `${value}px` }));
}

export function radiusVariables(scale: Record<string, number> = webRadii): CssVariable[] {
  return Object.entries(scale).map(([key, value]) => ({ name: `--${key}`, value: `${value}px` }));
}

export function fontSizeVariables(scale: Record<string, number> = webTypography.fontSize): CssVariable[] {
  return Object.entries(scale).map(([key, value]) => ({ name: `--${key}`, value: `${value}px` }));
}

export function lineHeightVariables(scale: Record<string, number> = webTypography.lineHeight): CssVariable[] {
  return Object.entries(scale).map(([key, value]) => ({ name: `--${key}`, value: `${value}px` }));
}

export function fontFamilyVariables(): CssVariable[] {
  return Object.entries(webTypography.fontFamily).map(([key, value]) => ({ name: `--${key}`, value: `'${value}'` }));
}

export function fontWeightVariables(): CssVariable[] {
  return Object.entries(webTypography.fontWeight).map(([key, value]) => ({ name: `--${key}`, value }));
}

export function staticVariables(): CssVariable[] {
  return [
    ...spacingVariables(),
    ...radiusVariables(),
    ...fontSizeVariables(),
    ...lineHeightVariables(),
    ...fontFamilyVariables(),
    ...fontWeightVariables(),
  ];
}

function toCssBlock(entries: CssVariable[], indent = '  ') {
  return entries.map(({ name, value }) => `${indent}${name}: ${value};`).join('\n');
}

export function buildCssVariablesFile() {
  return `/* Auto-generated by src/tokens/generate-css-variables.ts — do not edit by hand. */

:root {
${toCssBlock([...colorVariables(lightColors), ...staticVariables()])}
}

:root[data-theme='dark'] {
${toCssBlock(colorVariables(darkColors))}
}

@media (prefers-color-scheme: dark) {
  :root:not([data-theme='light']) {
${toCssBlock(colorVariables(darkColors), '    ')}
  }
}
`;
}
